"use strict"; // Strict mode on, takii choti galtiyan na hon

// Game State Object - Yeh game ka dimag hai
const GameState = {
    players: ['Red', 'Green', 'Yellow', 'Blue'],
        currentPlayerIndex: 0,
            diceValue: 0,
                isRolling: false,         // Roll hote waqt dubara click rokne ke liye
                    waitingForMove: false,    // Dice roll ke baad token move ka wait karna
                        diceFaces: ['⚀', '⚁', '⚂', '⚃', '⚄', '⚅']
                        };

                        // Jab pura HTML load ho jaye, tabhi JS chalega (Error-free approach)
                        document.addEventListener('DOMContentLoaded', () => {
                            
                                // 1. Board ke Tracks banana
                                    initializeTracks();

                                        // 2. Buttons aur Tokens par Event Listeners lagana
                                            setupEventListeners();

                                                // 3. Game start message
                                                    updateStatus(`${GameState.players[GameState.currentPlayerIndex]}'s Turn! Roll the dice.`);
                                                    });

                                                    // ==========================================
                                                    // BOARD SETUP LOGIC
                                                    // ==========================================
                                                    function initializeTracks() {
                                                        createTrackCells('top-track', 18, '#2ecc71');
                                                            createTrackCells('left-track', 18, '#e74c3c');
                                                                createTrackCells('right-track', 18, '#f1c40f');
                                                                    createTrackCells('bottom-track', 18, '#3498db');
                                                                    }

                                                                    function createTrackCells(trackId, count, safeColor) {
                                                                        const track = document.getElementById(trackId);
                                                                            if (!track) {
                                                                                    console.error(`Track ${trackId} not found!`);
                                                                                            return;
                                                                                                }

                                                                                                    for (let i = 0; i < count; i++) {
                                                                                                            let cell = document.createElement('div');
                                                                                                                    cell.classList.add('cell');
                                                                                                                            
                                                                                                                                    // Add safe zones visually
                                                                                                                                            if (trackId === 'top-track' && i % 3 === 1 && i > 2) cell.style.backgroundColor = safeColor;
                                                                                                                                                    if (trackId === 'bottom-track' && i % 3 === 1 && i < 15) cell.style.backgroundColor = safeColor;
                                                                                                                                                            if (trackId === 'left-track' && Math.floor(i / 6) === 1 && i > 6) cell.style.backgroundColor = safeColor;
                                                                                                                                                                    if (trackId === 'right-track' && Math.floor(i / 6) === 1 && i < 11) cell.style.backgroundColor = safeColor;
                                                                                                                                                                            
                                                                                                                                                                                    track.appendChild(cell);
                                                                                                                                                                                        }
                                                                                                                                                                                        }

                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                        // DICE ROLLING LOGIC
                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                        function setupEventListeners() {
                                                                                                                                                                                            const rollBtn = document.getElementById('roll-btn');
                                                                                                                                                                                                if (rollBtn) {
                                                                                                                                                                                                        rollBtn.addEventListener('click', handleDiceRoll);
                                                                                                                                                                                                            }

                                                                                                                                                                                                                // Tokens par click logic lagana
                                                                                                                                                                                                                    const tokens = document.querySelectorAll('.token');
                                                                                                                                                                                                                        tokens.forEach(token => {
                                                                                                                                                                                                                                token.addEventListener('click', handleTokenClick);
                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    function handleDiceRoll() {
                                                                                                                                                                                                                                        // Error Handling: Agar dice ghum raha hai ya player ne token move nahi kiya hai
                                                                                                                                                                                                                                            if (GameState.isRolling) return;
                                                                                                                                                                                                                                                if (GameState.waitingForMove) {
                                                                                                                                                                                                                                                        alert("Pehle apna token chalo!");
                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                        GameState.isRolling = true;
                                                                                                                                                                                                                                                                            const diceEl = document.getElementById('dice');
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    // Dice Animation (Quick Shuffle effect)
                                                                                                                                                                                                                                                                                        let shuffleCount = 0;
                                                                                                                                                                                                                                                                                            const shuffleInterval = setInterval(() => {
                                                                                                                                                                                                                                                                                                    const randomFace = Math.floor(Math.random() * 6);
                                                                                                                                                                                                                                                                                                            diceEl.innerText = GameState.diceFaces[randomFace];
                                                                                                                                                                                                                                                                                                                    diceEl.style.transform = `rotate(${Math.random() * 360}deg) scale(1.2)`;
                                                                                                                                                                                                                                                                                                                            shuffleCount++;

                                                                                                                                                                                                                                                                                                                                    // 10 baar shuffle hone ke baad final result aayega
                                                                                                                                                                                                                                                                                                                                            if (shuffleCount >= 10) {
                                                                                                                                                                                                                                                                                                                                                        clearInterval(shuffleInterval);
                                                                                                                                                                                                                                                                                                                                                                    finalizeDiceRoll(diceEl);
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                }, 50);
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                function finalizeDiceRoll(diceEl) {
                                                                                                                                                                                                                                                                                                                                                                                    // 1 se 6 tak random number generate karna
                                                                                                                                                                                                                                                                                                                                                                                        const finalRoll = Math.floor(Math.random() * 6) + 1;
                                                                                                                                                                                                                                                                                                                                                                                            GameState.diceValue = finalRoll;
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    // Final UI update
                                                                                                                                                                                                                                                                                                                                                                                                        diceEl.innerText = GameState.diceFaces[finalRoll - 1];
                                                                                                                                                                                                                                                                                                                                                                                                            diceEl.style.transform = 'rotate(0deg) scale(1)';
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    const currentPlayer = GameState.players[GameState.currentPlayerIndex];
                                                                                                                                                                                                                                                                                                                                                                                                                        updateStatus(`${currentPlayer} rolled a ${finalRoll}! Select your token.`);

                                                                                                                                                                                                                                                                                                                                                                                                                            GameState.isRolling = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                GameState.waitingForMove = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                    // Simulate waiting for move - Agar 6 nahi aaya aur koi token bahar nahi hai to turn pass kardo (Basic Rule)
                                                                                                                                                                                                                                                                                                                                                                                                                                        // Abhi ke liye hum sirf time ke sath turn change kar rahe hain:
                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    processTurnEnd(finalRoll);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 2000); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // TURN & TOKEN LOGIC
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                        function processTurnEnd(rollValue) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            GameState.waitingForMove = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Ludo Rule: 6 aane par bonus turn milta hai
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (rollValue === 6) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updateStatus(`${GameState.players[GameState.currentPlayerIndex]} gets a Bonus Turn! Roll again.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Next player ki turn
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                changeTurn();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function changeTurn() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        GameState.currentPlayerIndex = (GameState.currentPlayerIndex + 1) % 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const nextPlayer = GameState.players[GameState.currentPlayerIndex];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updateStatus(`${nextPlayer}'s Turn! Roll the dice.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Button ka color current player ke hisaab se change karna
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const colors = ['#e74c3c', '#2ecc71', '#f1c40f', '#3498db']; // Red, Green, Yellow, Blue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('roll-btn').style.backgroundColor = colors[GameState.currentPlayerIndex];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function handleTokenClick(event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!GameState.waitingForMove) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return; // Agar dice roll nahi hua hai to kuch mat karo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const clickedToken = event.target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const currentPlayerColor = GameState.players[GameState.currentPlayerIndex].toLowerCase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Check karo ki player ne apna hi token click kiya hai ya kisi aur ka
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (clickedToken.classList.contains(currentPlayerColor)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Token animation (chota sa bounce)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clickedToken.style.transform = 'translateY(-10px) scale(1.2)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    clickedToken.style.transform = 'translateY(0) scale(1)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 300);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Turn end ho gayi kyonki token chal diya (Visual simulation)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            processTurnEnd(GameState.diceValue);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert(`Bhai, cheating mat kar! Yeh ${currentPlayerColor} ka turn hai.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // UTILITY FUNCTIONS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function updateStatus(message) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const statusEl = document.getElementById('status');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (statusEl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            statusEl.innerText = message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                